name: grelen
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - tensorflow
  - torch
  - tensorboardx
  - pickle5
  - pip
  - pip:
      - logging
      - time
